# Generated by Django 4.2.7 on 2026-03-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_otp_exporttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='clock_in_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_out_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
