# Generated by Django 4.2.7 on 2026-04-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_otp_attempt_count_otp_max_attempts_alter_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('cancelled', 'Cancelled'), ('terminated', 'Terminated')], default='pending', max_length=10),
        ),
    ]
