# Generated by Django 4.2.7 on 2026-04-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_alter_deduction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='id_sequence',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated'), ('sacked', 'Sacked'), ('resigned', 'Resigned')], default='active', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('employee_id',), name='unique_employee_id', violation_error_message='Employee ID must be unique.'),
        ),
    ]
