# Generated by Django 4.2.7 on 2026-03-27 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_attendance_clock_in_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otp',
            name='max_attempts',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'OTP must be a 6-digit s number.')]),
        ),
    ]
